export const PUBLICATIONS_REQUESTED = 'PUBLICATIONS_REQUESTED';
export const CLEAR_PUBLICATIONS = 'CLEAR_PUBLICATIONS';

export const LIKED_PUBLICATIONS_REQUESTED = 'LIKED_PUBLICATIONS_REQUESTED';
export const CLEAR_LIKED_PUBLICATIONS = 'CLEAR_LIKED_PUBLICATIONS';

export const CURRENT_USER_REQUESTED = 'CURRENT_USER_REQUESTED';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const CURRENT_PUBLICATION = 'CURRENT_PUBLICATION';
export const CLEAR_CURRENT_PUBLICATION = 'CLEAR_CURRENT_PUBLICATION';

export const CURRENT_PUB_LIKE_EVENT = 'CURRENT_PUB_LIKE_EVENT';

export const LIKE = 'LIKE';
export const DISLIKE = 'DISLIKE';

export const PUB_IS_LOADING = 'PUB_IS_LOADING';
export const PUB_ERROR = 'PUB_ERROR';

export const LIKED_PUB_IS_LOADING = 'LIKED_PUB_IS_LOADING';
export const LIKED_PUB_ERROR = 'LIKED_PUB_ERROR';
