export const PUBLICATIONS_REQUESTED = "PUBLICATIONS_REQUESTED";
export const CLEAR_PUBLICATIONS = 'CLEAR_PUBLICATIONS';

export const LIKED_PUBLICATIONS_REQUESTED = "LIKED_PUBLICATIONS_REQUESTED";
export const CLEAR_LIKED_PUBLICATIONS = 'CLEAR_LIKED_PUBLICATIONS';

export const CURRENT_USER_REQUESTED = "CURRENT_USER_REQUESTED";
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const IS_LOADING = "IS_LOADING";
export const ERROR = "ERROR";
