export const PUBLICATIONS_REQUESTED = "PUBLICATIONS_REQUESTED";
export const LIKED_PUBLICATIONS_REQUESTED = "LIKED_PUBLICATIONS_REQUESTED";

export const IS_LOADING = "IS_LOADING";
export const ERROR = "ERROR";

export const CLEAR_PUBLICATIONS = 'CLEAR_PUBLICATIONS';
export const CLEAR_LIKED_PUBLICATIONS = 'CLEAR_LIKED_PUBLICATIONS';

